### ISSUE TITLE
Get error: "TypeError: dom.HTMLDocument is not a constructor"

### ISSUE THREAD

**Issue by chmelvv** [amurchick/AudioBooksDownload#3]
> "c:\Program Files\nodejs\node.exe" index https://audioknigi.club/eggers-deyv-sfera
Downloading https://audioknigi.club/eggers-deyv-sfera...
C:\Users\chmel\Downloads\AudioBooksDownload\node_modules\jsdom\lib\jsdom\browser\Window.js:41
  this._document = new dom.HTMLDocument({
                   ^

TypeError: dom.HTMLDocument is not a constructor
    at new Window (C:\Users\chmel\Downloads\AudioBooksDownload\node_modules\jsdom\lib\jsdom\browser\Window.js:41:20)
    at Object.exports.jsdom (C:\Users\chmel\Downloads\AudioBooksDownload\node_modules\jsdom\lib\jsdom.js:49:16)
    at processHTML (C:\Users\chmel\Downloads\AudioBooksDownload\node_modules\jsdom\lib\jsdom.js:218:24)
    at Request._callback (C:\Users\chmel\Downloads\AudioBooksDownload\node_modules\jsdom\lib\jsdom.js:193:7)
    at Request.self.callback (C:\Users\chmel\Downloads\AudioBooksDownload\node_modules\jsdom\node_modules\request\request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:194:7)
    at Request.<anonymous> (C:\Users\chmel\Downloads\AudioBooksDownload\node_modules\jsdom\node_modules\request\request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:191:7)
    at IncomingMessage.<anonymous> (C:\Users\chmel\Downloads\AudioBooksDownload\node_modules\jsdom\node_modules\request\request.js:1091:12)
    at Object.onceWrapper (events.js:293:19)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

**Comment by amurchick** [comment]
I rewrote the most of script code:
```Version 2.0.0
- node js version must be 8.0 or greater
- rewritten from generator functions/yield to await/async
- rewritten html body parsing - no more jQuery
- fix track numeration (now does not take from file name - use sequential numbers)
- parallel download of mp3 track (now hard coded 5 parallel downloads, in future will be configurable)
```

See https://github.com/amurchick/AudioBooksDownload/releases/tag/2.0.0

```
~/Documents/Develop/AudioBooksDownload # node index index https://audioknigi.club/eggers-deyv-sfera
Downloading https://audioknigi.club/eggers-deyv-sfera...
Download "http://audioknigi.club/rest/bid/41260"...
Title: Эггерс Дэйв - Сфера
Image: https://audioknigi.club/uploads/topics/preview/00/01/32/34/c2b464fd53.jpg
Tracks: 51
Download "https://audioknigi.club/uploads/topics/preview/00/01/32/34/c2b464fd53.jpg" to "Эггерс Дэйв - Сфера/c2b464fd53.jpg"...
Done "Эггерс Дэйв - Сфера/c2b464fd53.jpg": 43044 bytes
Download "https://get.sweetbook.net/b/41260/6eRU8lIOF6sjT7F6Iy7YSRx1A5m5S13vP5LqXGD8_Gk,/00_01_Annotatsiya.mp3" to "Эггерс Дэйв - Сфера/00_01_Annotatsiya.mp3"...
Download "https://get.sweetbook.net/b/41260/6eRU8lIOF6sjT7F6Iy7YSRx1A5m5S13vP5LqXGD8_Gk,/01_01_Sfera.mp3" to "Эггерс Дэйв - Сфера/01_01_Sfera.mp3"...
Download "https://get.sweetbook.net/b/41260/6eRU8lIOF6sjT7F6Iy7YSRx1A5m5S13vP5LqXGD8_Gk,/01_02_Sfera.mp3" to "Эггерс Дэйв - Сфера/01_02_Sfera.mp3"...
Download "https://get.sweetbook.net/b/41260/6eRU8lIOF6sjT7F6Iy7YSRx1A5m5S13vP5LqXGD8_Gk,/01_03_Sfera.mp3" to "Эггерс Дэйв - Сфера/01_03_Sfera.mp3"...
Download "https://get.sweetbook.net/b/41260/6eRU8lIOF6sjT7F6Iy7YSRx1A5m5S13vP5LqXGD8_Gk,/01_04_Sfera.mp3" to "Эггерс Дэйв - Сфера/01_04_Sfera.mp3"...
Done "Эггерс Дэйв - Сфера/00_01_Annotatsiya.mp3": 3189190 bytes
Download "https://get.sweetbook.net/b/41260/6eRU8lIOF6sjT7F6Iy7YSRx1A5m5S13vP5LqXGD8_Gk,/01_05_Sfera.mp3" to "Эггерс Дэйв - Сфера/01_05_Sfera.mp3"...
Done "Эггерс Дэйв - Сфера/01_01_Sfera.mp3": 8095395 bytes
Download "https://get.sweetbook.net/b/41260/6eRU8lIOF6sjT7F6Iy7YSRx1A5m5S13vP5LqXGD8_Gk,/01_06_Sfera.mp3" to "Эггерс Дэйв - Сфера/01_06_Sfera.mp3"...
Done "Эггерс Дэйв - Сфера/01_03_Sfera.mp3": 9527533 bytes
Download "https://get.sweetbook.net/b/41260/6eRU8lIOF6sjT7F6Iy7YSRx1A5m5S13vP5LqXGD8_Gk,/01_07_Sfera.mp3" to "Эггерс Дэйв - Сфера/01_07_Sfera.mp3"...
Done "Эггерс Дэйв - Сфера/01_04_Sfera.mp3": 10490719 bytes
Download "https://get.sweetbook.net/b/41260/6eRU8lIOF6sjT7F6Iy7YSRx1A5m5S13vP5LqXGD8_Gk,/01_08_Sfera.mp3" to "Эггерс Дэйв - Сфера/01_08_Sfera.mp3"...
Done "Эггерс Дэйв - Сфера/01_05_Sfera.mp3": 8932150 bytes
Download "https://get.sweetbook.net/b/41260/6eRU8lIOF6sjT7F6Iy7YSRx1A5m5S13vP5LqXGD8_Gk,/01_09_Sfera.mp3" to "Эггерс Дэйв - Сфера/01_09_Sfera.mp3"...
Done "Эггерс Дэйв - Сфера/01_02_Sfera.mp3": 13911297 bytes
Download "https://get.sweetbook.net/b/41260/6eRU8lIOF6sjT7F6Iy7YSRx1A5m5S13vP5LqXGD8_Gk,/01_10_Sfera.mp3" to "Эггерс Дэйв - Сфера/01_10_Sfera.mp3"...
Done "Эггерс Дэйв - Сфера/01_07_Sfera.mp3": 8269057 bytes
Download "https://get.sweetbook.net/b/41260/6eRU8lIOF6sjT7F6Iy7YSRx1A5m5S13vP5LqXGD8_Gk,/01_11_Sfera.mp3" to "Эггерс Дэйв - Сфера/01_11_Sfera.mp3"...
Done "Эггерс Дэйв - Сфера/01_06_Sfera.mp3": 10035144 bytes
Download "https://get.sweetbook.net/b/41260/6eRU8lIOF6sjT7F6Iy7YSRx1A5m5S13vP5LqXGD8_Gk,/01_12_Sfera.mp3" to "Эггерс Дэйв - Сфера/01_12_Sfera.mp3"...
Done "Эггерс Дэйв - Сфера/01_10_Sfera.mp3": 9984780 bytes
Download "https://get.sweetbook.net/b/41260/6eRU8lIOF6sjT7F6Iy7YSRx1A5m5S13vP5LqXGD8_Gk,/01_13_Sfera.mp3" to "Эггерс Дэйв - Сфера/01_13_Sfera.mp3"...
Done "Эггерс Дэйв - Сфера/01_08_Sfera.mp3": 11519526 bytes
Download "https://get.sweetbook.net/b/41260/6eRU8lIOF6sjT7F6Iy7YSRx1A5m5S13vP5LqXGD8_Gk,/01_14_Sfera.mp3" to "Эггерс Дэйв - Сфера/01_14_Sfera.mp3"...
Done "Эггерс Дэйв - Сфера/01_11_Sfera.mp3": 8007206 bytes
Download "https://get.sweetbook.net/b/41260/6eRU8lIOF6sjT7F6Iy7YSRx1A5m5S13vP5LqXGD8_Gk,/01_15_Sfera.mp3" to "Эггерс Дэйв - Сфера/01_15_Sfera.mp3"...
Done "Эггерс Дэйв - Сфера/01_09_Sfera.mp3": 11988267 bytes
Download "https://get.sweetbook.net/b/41260/6eRU8lIOF6sjT7F6Iy7YSRx1A5m5S13vP5LqXGD8_Gk,/01_16_Sfera.mp3" to "Эггерс Дэйв - Сфера/01_16_Sfera.mp3"...
Done "Эггерс Дэйв - Сфера/01_13_Sfera.mp3": 10577655 bytes
Download "https://get.sweetbook.net/b/41260/6eRU8lIOF6sjT7F6Iy7YSRx1A5m5S13vP5LqXGD8_Gk,/01_17_Sfera.mp3" to "Эггерс Дэйв - Сфера/01_17_Sfera.mp3"...
Done "Эггерс Дэйв - Сфера/01_12_Sfera.mp3": 13674733 bytes
Download "https://get.sweetbook.net/b/41260/6eRU8lIOF6sjT7F6Iy7YSRx1A5m5S13vP5LqXGD8_Gk,/01_18_Sfera.mp3" to "Эггерс Дэйв - Сфера/01_18_Sfera.mp3"...
Done "Эггерс Дэйв - Сфера/01_14_Sfera.mp3": 9884470 bytes
Download "https://get.sweetbook.net/b/41260/6eRU8lIOF6sjT7F6Iy7YSRx1A5m5S13vP5LqXGD8_Gk,/01_19_Sfera.mp3" to "Эггерс Дэйв - Сфера/01_19_Sfera.mp3"...
Done "Эггерс Дэйв - Сфера/01_16_Sfera.mp3": 10427190 bytes
Download "https://get.sweetbook.net/b/41260/6eRU8lIOF6sjT7F6Iy7YSRx1A5m5S13vP5LqXGD8_Gk,/01_20_Sfera.mp3" to "Эггерс Дэйв - Сфера/01_20_Sfera.mp3"...
Done "Эггерс Дэйв - Сфера/01_15_Sfera.mp3": 11805619 bytes
Done "Эггерс Дэйв - Сфера/01_18_Sfera.mp3": 9404862 bytes
Download "https://get.sweetbook.net/b/41260/6eRU8lIOF6sjT7F6Iy7YSRx1A5m5S13vP5LqXGD8_Gk,/01_21_Sfera.mp3" to "Эггерс Дэйв - Сфера/01_21_Sfera.mp3"...
Download "https://get.sweetbook.net/b/41260/6eRU8lIOF6sjT7F6Iy7YSRx1A5m5S13vP5LqXGD8_Gk,/01_22_Sfera.mp3" to "Эггерс Дэйв - Сфера/01_22_Sfera.mp3"...
Done "Эггерс Дэйв - Сфера/01_19_Sfera.mp3": 7936571 bytes
Download "https://get.sweetbook.net/b/41260/6eRU8lIOF6sjT7F6Iy7YSRx1A5m5S13vP5LqXGD8_Gk,/01_23_Sfera.mp3" to "Эггерс Дэйв - Сфера/01_23_Sfera.mp3"...
Done "Эггерс Дэйв - Сфера/01_17_Sfera.mp3": 10790605 bytes
Download "https://get.sweetbook.net/b/41260/6eRU8lIOF6sjT7F6Iy7YSRx1A5m5S13vP5LqXGD8_Gk,/01_24_Sfera.mp3" to "Эггерс Дэйв - Сфера/01_24_Sfera.mp3"...
Done "Эггерс Дэйв - Сфера/01_20_Sfera.mp3": 13256773 bytes
Download "https://get.sweetbook.net/b/41260/6eRU8lIOF6sjT7F6Iy7YSRx1A5m5S13vP5LqXGD8_Gk,/01_25_Sfera.mp3" to "Эггерс Дэйв - Сфера/01_25_Sfera.mp3"...
Done "Эггерс Дэйв - Сфера/01_23_Sfera.mp3": 9290550 bytes
Download "https://get.sweetbook.net/b/41260/6eRU8lIOF6sjT7F6Iy7YSRx1A5m5S13vP5LqXGD8_Gk,/01_26_Sfera.mp3" to "Эггерс Дэйв - Сфера/01_26_Sfera.mp3"...
Done "Эггерс Дэйв - Сфера/01_22_Sfera.mp3": 12220026 bytes
Download "https://get.sweetbook.net/b/41260/6eRU8lIOF6sjT7F6Iy7YSRx1A5m5S13vP5LqXGD8_Gk,/01_27_Sfera.mp3" to "Эггерс Дэйв - Сфера/01_27_Sfera.mp3"...
Done "Эггерс Дэйв - Сфера/01_21_Sfera.mp3": 13615173 bytes
Download "https://get.sweetbook.net/b/41260/6eRU8lIOF6sjT7F6Iy7YSRx1A5m5S13vP5LqXGD8_Gk,/01_28_Sfera.mp3" to "Эггерс Дэйв - Сфера/01_28_Sfera.mp3"...
Done "Эггерс Дэйв - Сфера/01_26_Sfera.mp3": 8166239 bytes
Download "https://get.sweetbook.net/b/41260/6eRU8lIOF6sjT7F6Iy7YSRx1A5m5S13vP5LqXGD8_Gk,/02_01_Sfera.mp3" to "Эггерс Дэйв - Сфера/02_01_Sfera.mp3"...
Done "Эггерс Дэйв - Сфера/01_25_Sfera.mp3": 9660444 bytes
Download "https://get.sweetbook.net/b/41260/6eRU8lIOF6sjT7F6Iy7YSRx1A5m5S13vP5LqXGD8_Gk,/02_02_Sfera.mp3" to "Эггерс Дэйв - Сфера/02_02_Sfera.mp3"...
Done "Эггерс Дэйв - Сфера/01_24_Sfera.mp3": 14430194 bytes
Download "https://get.sweetbook.net/b/41260/6eRU8lIOF6sjT7F6Iy7YSRx1A5m5S13vP5LqXGD8_Gk,/02_03_Sfera.mp3" to "Эггерс Дэйв - Сфера/02_03_Sfera.mp3"...
Done "Эггерс Дэйв - Сфера/02_01_Sfera.mp3": 11642615 bytes
Download "https://get.sweetbook.net/b/41260/6eRU8lIOF6sjT7F6Iy7YSRx1A5m5S13vP5LqXGD8_Gk,/02_04_Sfera.mp3" to "Эггерс Дэйв - Сфера/02_04_Sfera.mp3"...
Done "Эггерс Дэйв - Сфера/01_28_Sfera.mp3": 11266870 bytes
Done "Эггерс Дэйв - Сфера/01_27_Sfera.mp3": 12646553 bytes
Download "https://get.sweetbook.net/b/41260/6eRU8lIOF6sjT7F6Iy7YSRx1A5m5S13vP5LqXGD8_Gk,/02_05_Sfera.mp3" to "Эггерс Дэйв - Сфера/02_05_Sfera.mp3"...
Download "https://get.sweetbook.net/b/41260/6eRU8lIOF6sjT7F6Iy7YSRx1A5m5S13vP5LqXGD8_Gk,/02_06_Sfera.mp3" to "Эггерс Дэйв - Сфера/02_06_Sfera.mp3"...
Done "Эггерс Дэйв - Сфера/02_02_Sfera.mp3": 7847546 bytes
Download "https://get.sweetbook.net/b/41260/6eRU8lIOF6sjT7F6Iy7YSRx1A5m5S13vP5LqXGD8_Gk,/02_07_Sfera.mp3" to "Эггерс Дэйв - Сфера/02_07_Sfera.mp3"...
Done "Эггерс Дэйв - Сфера/02_03_Sfera.mp3": 10192924 bytes
Download "https://get.sweetbook.net/b/41260/6eRU8lIOF6sjT7F6Iy7YSRx1A5m5S13vP5LqXGD8_Gk,/02_08_Sfera.mp3" to "Эггерс Дэйв - Сфера/02_08_Sfera.mp3"...
Done "Эггерс Дэйв - Сфера/02_05_Sfera.mp3": 10522902 bytes
Done "Эггерс Дэйв - Сфера/02_06_Sfera.mp3": 7657583 bytes
Download "https://get.sweetbook.net/b/41260/6eRU8lIOF6sjT7F6Iy7YSRx1A5m5S13vP5LqXGD8_Gk,/02_09_Sfera.mp3" to "Эггерс Дэйв - Сфера/02_09_Sfera.mp3"...
Download "https://get.sweetbook.net/b/41260/6eRU8lIOF6sjT7F6Iy7YSRx1A5m5S13vP5LqXGD8_Gk,/02_10_Sfera.mp3" to "Эггерс Дэйв - Сфера/02_10_Sfera.mp3"...
Done "Эггерс Дэйв - Сфера/02_07_Sfera.mp3": 8034791 bytes
Done "Эггерс Дэйв - Сфера/02_04_Sfera.mp3": 7595516 bytes
Download "https://get.sweetbook.net/b/41260/6eRU8lIOF6sjT7F6Iy7YSRx1A5m5S13vP5LqXGD8_Gk,/02_11_Sfera.mp3" to "Эггерс Дэйв - Сфера/02_11_Sfera.mp3"...
Download "https://get.sweetbook.net/b/41260/6eRU8lIOF6sjT7F6Iy7YSRx1A5m5S13vP5LqXGD8_Gk,/02_12_Sfera.mp3" to "Эггерс Дэйв - Сфера/02_12_Sfera.mp3"...
Done "Эггерс Дэйв - Сфера/02_08_Sfera.mp3": 8149312 bytes
Download "https://get.sweetbook.net/b/41260/6eRU8lIOF6sjT7F6Iy7YSRx1A5m5S13vP5LqXGD8_Gk,/02_13_Sfera.mp3" to "Эггерс Дэйв - Сфера/02_13_Sfera.mp3"...
Done "Эггерс Дэйв - Сфера/02_10_Sfera.mp3": 7152688 bytes
Download "https://get.sweetbook.net/b/41260/6eRU8lIOF6sjT7F6Iy7YSRx1A5m5S13vP5LqXGD8_Gk,/02_14_Sfera.mp3" to "Эггерс Дэйв - Сфера/02_14_Sfera.mp3"...
Done "Эггерс Дэйв - Сфера/02_09_Sfera.mp3": 7932809 bytes
Download "https://get.sweetbook.net/b/41260/6eRU8lIOF6sjT7F6Iy7YSRx1A5m5S13vP5LqXGD8_Gk,/02_15_Sfera.mp3" to "Эггерс Дэйв - Сфера/02_15_Sfera.mp3"...
Done "Эггерс Дэйв - Сфера/02_11_Sfera.mp3": 8026432 bytes
Download "https://get.sweetbook.net/b/41260/6eRU8lIOF6sjT7F6Iy7YSRx1A5m5S13vP5LqXGD8_Gk,/02_16_Sfera.mp3" to "Эггерс Дэйв - Сфера/02_16_Sfera.mp3"...
Done "Эггерс Дэйв - Сфера/02_14_Sfera.mp3": 10422383 bytes
Download "https://get.sweetbook.net/b/41260/6eRU8lIOF6sjT7F6Iy7YSRx1A5m5S13vP5LqXGD8_Gk,/02_17_Sfera.mp3" to "Эггерс Дэйв - Сфера/02_17_Sfera.mp3"...
Done "Эггерс Дэйв - Сфера/02_12_Sfera.mp3": 11841773 bytes
Download "https://get.sweetbook.net/b/41260/6eRU8lIOF6sjT7F6Iy7YSRx1A5m5S13vP5LqXGD8_Gk,/02_18_Sfera.mp3" to "Эггерс Дэйв - Сфера/02_18_Sfera.mp3"...
Done "Эггерс Дэйв - Сфера/02_13_Sfera.mp3": 8857335 bytes
Download "https://get.sweetbook.net/b/41260/6eRU8lIOF6sjT7F6Iy7YSRx1A5m5S13vP5LqXGD8_Gk,/02_19_Sfera.mp3" to "Эггерс Дэйв - Сфера/02_19_Sfera.mp3"...
Done "Эггерс Дэйв - Сфера/02_15_Sfera.mp3": 12297139 bytes
Download "https://get.sweetbook.net/b/41260/6eRU8lIOF6sjT7F6Iy7YSRx1A5m5S13vP5LqXGD8_Gk,/02_20_Sfera.mp3" to "Эггерс Дэйв - Сфера/02_20_Sfera.mp3"...
Done "Эггерс Дэйв - Сфера/02_16_Sfera.mp3": 8585453 bytes
Download "https://get.sweetbook.net/b/41260/6eRU8lIOF6sjT7F6Iy7YSRx1A5m5S13vP5LqXGD8_Gk,/03_Sfera.mp3" to "Эггерс Дэйв - Сфера/03_Sfera.mp3"...
Done "Эггерс Дэйв - Сфера/02_17_Sfera.mp3": 7674510 bytes
Download "https://get.sweetbook.net/b/41260/6eRU8lIOF6sjT7F6Iy7YSRx1A5m5S13vP5LqXGD8_Gk,/04_Blagodarnosti.mp3" to "Эггерс Дэйв - Сфера/04_Blagodarnosti.mp3"...
Done "Эггерс Дэйв - Сфера/04_Blagodarnosti.mp3": 996578 bytes
Done "Эггерс Дэйв - Сфера/03_Sfera.mp3": 3511631 bytes
Done "Эггерс Дэйв - Сфера/02_18_Sfera.mp3": 12254298 bytes
Done "Эггерс Дэйв - Сфера/02_19_Sfera.mp3": 12799317 bytes
Done "Эггерс Дэйв - Сфера/02_20_Sfera.mp3": 10048101 bytes
~/Documents/Develop/AudioBooksDownload # 
```

Please try and give me feedback, please.
