### ISSUE TITLE
Problem with colon in book`s name

### ISSUE THREAD

**Issue by chmelvv** [amurchick/AudioBooksDownload#5]
```
node index https://audioknigi.club/kovi-stiven-fokus-dostizhenie-prioritetnyh-celey
Downloading https://audioknigi.club/kovi-stiven-fokus-dostizhenie-prioritetnyh-celey...
Download "http://audioknigi.club/rest/bid/15758"...
Title: Кови Стивен - Фокус: достижение приоритетных целей
Image: https://audioknigi.club/uploads/topics/preview/00/00/38/42/befe71eaf7.jpg
Tracks: 29
processFunction() error Error: ENOENT: no such file or directory, mkdir 'C:\audiobook\AudioBooksDownload\Кови Стивен - Фокус: достижение приоритетных целей'
    at Object.fs.mkdirSync (fs.js:890:18)
    at processFunction (C:\audiobook\AudioBooksDownload\index.js:174:10)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
```

**Comment by amurchick** [comment]
Fixed
