### ISSUE TITLE
SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by maks123** [amurchick/AudioBooksDownload#6]
Добрый день.
При попытке скачать аудиокнигу появляется ошибка.
```
maksim@ubu1604-test:~/AudioBooksDownload-master$ node index http://audioknigi.club/kori-dzheyms-probuzhdenie-leviafana
/home/maksim/AudioBooksDownload-master/index.js:8
const { JSDOM } = jsdom;
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
maksim@ubu1604-test:~/AudioBooksDownload-master$
```
Как исправить ее?

os: ubuntu 16.04
node: v4.2.6

Заранее спасибо

**Comment by andymilga** [comment]
@maks123 для работы скрипта нужна нода выше 8.0.
4.2 слишкам стара.

**Comment by maks123** [comment]
Добрый день.
Снова ошибка уже на 8 версии.

```
maksim@ubu1604-test:/opt/audiobookdownloader$ node -v
v8.11.1
maksim@ubu1604-test:/opt/audiobookdownloader$ node index https://audioknigi.club/kori-dzheyms-probuzhdenie-leviafana
Downloading https://audioknigi.club/kori-dzheyms-probuzhdenie-leviafana...
main() error: TypeError: whatwgURL.serializeURLOrigin is not a function
    at new DocumentImpl (/opt/audiobookdownloader/node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:225:30)
    at Object.setup (/opt/audiobookdownloader/node_modules/jsdom/lib/jsdom/living/generated/Document.js:2801:14)
    at Object.create (/opt/audiobookdownloader/node_modules/jsdom/lib/jsdom/living/generated/Document.js:2762:16)
    at new Window (/opt/audiobookdownloader/node_modules/jsdom/lib/jsdom/browser/Window.js:86:29)
    at new JSDOM (/opt/audiobookdownloader/node_modules/jsdom/lib/api.js:41:20)
    at request.then.res (/opt/audiobookdownloader/node_modules/jsdom/lib/api.js:168:16)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
maksim@ubu1604-test:/opt/audiobookdownloader$
```

**Comment by andymilga** [comment]
Что вывод npm install говорит?

**Comment by maks123** [comment]
```
maksim@ubu1604-test:/opt/audiobookdownloader$ sudo  npm i -g npm
/usr/bin/npm -> /usr/lib/node_modules/npm/bin/npm-cli.js
/usr/bin/npx -> /usr/lib/node_modules/npm/bin/npx-cli.js
+ npm@6.0.0
added 244 packages, removed 40 packages and updated 121 packages in 30.952s
maksim@ubu1604-test:/opt/audiobookdownloader$ 
```
Обновил npm  и все заработало.
Спасибо

**Comment by amurchick** [comment]
@andymilga спасибо!
